### ISSUE TITLE
Typo found

### ISSUE THREAD

**Issue by agb94** [UNIST-LOFT/SimAPR#1]
Hi, thank you for providing this tool :-)
While inspecting your code, I noticed a minor typo: 'gosn' should be corrected to 'gson'. Thanks.

https://github.com/UNIST-LOFT/SimAPR/blob/390f74e4f13100751fbce2c38068c41da63c3ffe/SimAPR/script/d4j_run_test.py#L67C1-L68C1

**Comment by FreddyYJ** [comment]
Thanks for the report, I fixed the typo.
